# fly.toml app configuration file generated for celestai-ass on 2023-06-09T06:08:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "celestai-ass"
primary_region = "sea"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
